"""LLM providers for deep security analysis.

Each provider wraps a specific AI API and implements the abstract
:class:`LLMProvider` interface.  All HTTP communication is done via the
standard library ``urllib.request`` — no third-party HTTP libraries are needed.
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------

ANALYSIS_PROMPT_TEMPLATE: str = """\
You are a cybersecurity analyst. Analyze these scan results and provide:
1. A list of security findings with severity (critical/high/medium/low/info)
2. Specific recommendations for each finding
3. An overall risk assessment

Scan Results:
{results_json}

Rules-based findings already identified:
{rules_json}

Provide your analysis as JSON:
{{
  "findings": [{{"severity": "...", "title": "...", "description": "...", "recommendation": "..."}}],
  "summary": "overall risk assessment paragraph"
}}
"""


def _build_prompt(results: dict, rules_findings: list) -> str:
    """Build the analysis prompt for the LLM.

    Parameters
    ----------
    results : dict
        Raw scan results from all plugins.
    rules_findings : list
        Findings already generated by the rules engine.

    Returns
    -------
    str
        Formatted prompt string.
    """
    results_json = json.dumps(results, indent=2, default=str)
    rules_json = json.dumps(
        [
            {"severity": f.severity, "title": f.title}
            for f in rules_findings
        ],
        indent=2,
    )
    return ANALYSIS_PROMPT_TEMPLATE.format(
        results_json=results_json, rules_json=rules_json
    )


# ---------------------------------------------------------------------------
# Base class
# ---------------------------------------------------------------------------


class LLMProvider(ABC):
    """Base class for LLM providers.

    Subclasses must implement :meth:`analyze`.
    """

    @abstractmethod
    def analyze(self, results: dict, rules_findings: list) -> str:
        """Send *results* and *rules_findings* to the LLM and return analysis text.

        Parameters
        ----------
        results : dict
            Raw scan results keyed by plugin name.
        rules_findings : list
            Findings already produced by the rules engine.

        Returns
        -------
        str
            Raw text response from the LLM.
        """
        ...


# ---------------------------------------------------------------------------
# Concrete providers
# ---------------------------------------------------------------------------


class ClaudeProvider(LLMProvider):
    """Anthropic Claude API provider."""

    API_URL: str = "https://api.anthropic.com/v1/messages"

    def __init__(
        self, api_key: str, model: str = "claude-sonnet-4-20250514"
    ) -> None:
        self.api_key = api_key
        self.model = model

    def analyze(self, results: dict, rules_findings: list) -> str:
        """Send analysis request to Claude."""
        prompt = _build_prompt(results, rules_findings)

        body: dict[str, Any] = {
            "model": self.model,
            "max_tokens": 2000,
            "messages": [{"role": "user", "content": prompt}],
        }

        request = urllib.request.Request(
            self.API_URL,
            data=json.dumps(body).encode("utf-8"),
            headers={
                "x-api-key": self.api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                data = json.loads(response.read().decode("utf-8"))
                # Extract text from content blocks
                content_blocks = data.get("content", [])
                texts: list[str] = [
                    block.get("text", "")
                    for block in content_blocks
                    if block.get("type") == "text"
                ]
                return "\n".join(texts)
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            logger.error("Claude API HTTP %s: %s", e.code, error_body)
            return f"Claude API error (HTTP {e.code}): {error_body}"
        except Exception as e:
            logger.exception("Claude API request failed: %s", e)
            return f"Claude API error: {e}"


class GeminiProvider(LLMProvider):
    """Google Gemini API provider."""

    BASE_URL: str = "https://generativelanguage.googleapis.com/v1beta/models"

    def __init__(
        self, api_key: str, model: str = "gemini-2.0-flash"
    ) -> None:
        self.api_key = api_key
        self.model = model

    def analyze(self, results: dict, rules_findings: list) -> str:
        """Send analysis request to Gemini."""
        prompt = _build_prompt(results, rules_findings)
        url = f"{self.BASE_URL}/{self.model}:generateContent?key={self.api_key}"

        body: dict[str, Any] = {
            "contents": [{"parts": [{"text": prompt}]}],
        }

        request = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={"content-type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                data = json.loads(response.read().decode("utf-8"))
                candidates = data.get("candidates", [])
                parts = (
                    candidates[0]
                    .get("content", {})
                    .get("parts", [])
                    if candidates
                    else []
                )
                texts: list[str] = [
                    p.get("text", "") for p in parts if "text" in p
                ]
                return "\n".join(texts)
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            logger.error("Gemini API HTTP %s: %s", e.code, error_body)
            return f"Gemini API error (HTTP {e.code}): {error_body}"
        except Exception as e:
            logger.exception("Gemini API request failed: %s", e)
            return f"Gemini API error: {e}"


class OpenAIProvider(LLMProvider):
    """OpenAI API provider (also works with compatible APIs).

    Parameters
    ----------
    api_key : str
        API key for authentication.
    model : str
        Model identifier (default ``gpt-4o``).
    base_url : str
        Base URL for the API.  Change to a custom endpoint for compatibility
        with Azure OpenAI, Ollama, or other OpenAI-compatible providers.
    """

    def __init__(
        self,
        api_key: str,
        model: str = "gpt-4o",
        base_url: str = "https://api.openai.com/v1",
    ) -> None:
        self.api_key = api_key
        self.model = model
        self.base_url = base_url

    def analyze(self, results: dict, rules_findings: list) -> str:
        """Send analysis request to OpenAI."""
        prompt = _build_prompt(results, rules_findings)
        url = f"{self.base_url}/chat/completions"

        body: dict[str, Any] = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 2000,
        }

        request = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={
                "authorization": f"Bearer {self.api_key}",
                "content-type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                data = json.loads(response.read().decode("utf-8"))
                choices = data.get("choices", [])
                if choices:
                    message = choices[0].get("message", {})
                    return message.get("content", "")
                return "No response from OpenAI"
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            logger.error("OpenAI API HTTP %s: %s", e.code, error_body)
            return f"OpenAI API error (HTTP {e.code}): {error_body}"
        except Exception as e:
            logger.exception("OpenAI API request failed: %s", e)
            return f"OpenAI API error: {e}"


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

_PROVIDER_REGISTRY: dict[str, type[LLMProvider]] = {
    "claude": ClaudeProvider,
    "gemini": GeminiProvider,
    "openai": OpenAIProvider,
}


def get_provider(
    name: str, api_key: str, model: str | None = None
) -> LLMProvider:
    """Factory function to get an LLM provider by name.

    Parameters
    ----------
    name : str
        Provider name: ``"claude"``, ``"gemini"``, or ``"openai"``.
    api_key : str
        API key for the provider.
    model : str or None
        Optional model override.  Uses the provider default if ``None``.

    Returns
    -------
    LLMProvider
        An instance of the requested provider.

    Raises
    ------
    ValueError
        If *name* is not a recognised provider.
    """
    cls = _PROVIDER_REGISTRY.get(name.lower())
    if cls is None:
        raise ValueError(
            f"Unknown provider: {name!r}. Available: {', '.join(_PROVIDER_REGISTRY)}"
        )
    if model:
        return cls(api_key, model)
    return cls(api_key)
